A,B=input().split()
A=float(A)
B=float(B)
P=(B*B)-(A*A)
C=(P)**0.5
k=A+B+C
l=0.5*C*A
print("Alas =", round(C),"cm")
print("Tinggi =", round(A),"cm")
print("Keliling =", round(k),"cm")
print("Luas =", round(l),"cm\n")
A1=int(input())
B1=int(input())
P1=(B1*B1)-(A1*A1)
C1=(P1)**0.5
k1=A1+B1+C1
l1=0.5*C1*A1
print("Alas =", round(C1),"cm")
print("Tinggi =", round(A1),"cm")
print("Keliling =", round(k1),"cm")
print("Luas =", round(l1),"cm\n")