na  = input("Nama                :")
ni  = input("NIM                 :")
k   = input("Kelas Paralel       :")
ttl = input("Tempat/Tanggal Lahir:")
a   = input("Alamat              :")
h   = input("Hobby               :")
no  = input("No. HP              :")
print("\n")
print("Nama                :",na)
print("NIM                 :",ni)
print("Kelas Paralel       :",k)
print("Tempat/Tanggal Lahir:",ttl)
print("Alamat              :",a)
print("Hobby               :",h)
print("No. HP              :",no)
